INSERT INTO STUDENT1
SELECT *
FROM STUDENT
WHERE STUDENT_ID IN (SELECT STUDENT_ID
                     FROM (SELECT STUDENT_ID, COUNT(MARK) AS COUNT
                           FROM EXAM_MARKS
                           WHERE MARK > 3
                           GROUP BY STUDENT_ID) AS A
                     WHERE A.COUNT > 5);

CREATE TABLE STUDENT1 LIKE STUDENT;

SELECT *
FROM STUDENT1;

DROP TABLE STUDENT1;