UPDATE STUDENT
SET STIPEND = STIPEND * 1.2
WHERE STUDENT_ID IN (SELECT STUDENT_ID
                     FROM (SELECT STUDENT_ID, SUM(MARK) AS SUM FROM EXAM_MARKS GROUP BY STUDENT_ID) AS A
                     WHERE A.SUM > 50);